# This file is generated by nerve's release workflow (scripts/update-tap-formula.sh).
# DO NOT EDIT by hand — changes will be overwritten on the next release.
class Nerve < Formula
  desc "Git-worktree manager that allocates ports and wires up Claude Code hooks"
  homepage "https://github.com/mascah/nerve"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mascah/nerve/releases/download/v0.1.1/nerve_0.1.1_darwin_arm64.tar.gz"
      sha256 "40de6c792b707fe74bb24d286848ebd6ab007f014ca4e85a714dbe304caf3db6"
    end
    on_intel do
      url "https://github.com/mascah/nerve/releases/download/v0.1.1/nerve_0.1.1_darwin_amd64.tar.gz"
      sha256 "59cfa9c4d4998d1bd8d66829a068af2cea1fb5838b1c9fb57825030298e74539"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mascah/nerve/releases/download/v0.1.1/nerve_0.1.1_linux_arm64.tar.gz"
      sha256 "c0d8205553ec8ef69f0fef70633e8b29bc2ea91aa7c607032e1f9c2599857efd"
    end
    on_intel do
      url "https://github.com/mascah/nerve/releases/download/v0.1.1/nerve_0.1.1_linux_amd64.tar.gz"
      sha256 "c4d624ac690ea195b163f9c5139085a8735c573dae0bc0334906cc521a50bad1"
    end
  end

  def install
    bin.install "nerve"
  end

  test do
    assert_match "0.1.1", shell_output("#{bin}/nerve version")
  end
end
